net.sf.jasperreports.extension.registry.factory.simple.font.families=net.sf.jasperreports.engine.fonts.SimpleFontExtensionsRegistryFactory
net.sf.jasperreports.extension.simple.font.families.khmer=fonts/fonts.xml
net.sf.jasperreports.export.pdf.force.linebreak.policy=true
org.eclipse.jdt.core.compiler.processAnnotations=disabled